"""Fixed labels. Wording is part of the scientific safety contract."""

SIMULATION_BANNER = (
    "SIMULATION RESULT — NOT CLINICAL EVIDENCE, DIAGNOSIS, OR MEDICAL ADVICE."
)
MODEL_PREDICTION = "MODEL PREDICTION"
SYNTHETIC_DATA = "SYNTHETIC DATA"
SIMPLIFIED_MODEL = "SIMPLIFIED COMPUTATIONAL MODEL"
SOFTWARE_VALIDATION = "VALIDATED FOR SOFTWARE CORRECTNESS"
DEMO_PLACEHOLDER = "DEMO / PLACEHOLDER"
DATA_CONDITIONED = "DATA-CONDITIONED COMPUTATIONAL MODEL"

SOFTWARE_VERSION = "0.1.0"
